### ISSUE TITLE
pushalot <-> honorbuddy not pushing chat messages

### ISSUE THREAD

**Issue by mariodigital** [Mirabis/PushHub#6]
Hi, I am not getting any chat events pushes through pushalot, only for player and bot. Also i receive each message 3 times in pushalot. Any chance for a fix? Thanks for the plugin

**Comment by Mirabis** [comment]
Could be HB API, WoW or Pushover api changed over time. I'd have to double check, can't really give an eta on that now :(

**Comment by mariodigital** [comment]
Well good News is that the triple message bug seemed to sort it self, because since this morning i only receive every Event once. And I also received a notification for a whisper i got. Just the Chats are not getting picked up. Thank you for checking btw!

**Comment by Mirabis** [comment]
Closing this now that Honorbuddy is no longer available.
